heat_template_version: 2015-04-30

parameters:
  undercloud_flavor:
    type: string
  undercloud_image:
    type: string
  key_name:
    type: string
  undercloud_name:
    type: string
  undercloud_user_data_format:
    type: string
  undercloud_user_data:
    type: string
  private_net:
    type: string
  networks:
    type: json
  external_net:
    type: string

resources:
  undercloud_ports:
    type: OS::OVB::UndercloudPorts
    properties:
      undercloud_name: {get_param: undercloud_name}
      private_net: {get_param: private_net}
      networks: {get_param: networks}

  undercloud_server:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: undercloud_flavor}
      image: {get_param: undercloud_image}
      key_name: {get_param: key_name}
      networks: {get_attr: [undercloud_ports, ports]}
      name: {get_param: undercloud_name}
      user_data_format: {get_param: undercloud_user_data_format}
      user_data: {get_param: undercloud_user_data}

  undercloud_floating_ip:
    type: OS::OVB::UndercloudFloating
    properties:
      external_net: {get_param: external_net}
      undercloud_port:
        get_attr:
        - undercloud_server
        - addresses
        - {get_param: private_net}
        - 0
        - port

outputs:
  undercloud_host_floating_ip:
    description: "floating ip of the undercloud instance"
    value:
      get_attr: [undercloud_floating_ip, undercloud_host]
  undercloud_host_private_ip:
    description: "ip of the undercloud instance on the private network"
    value:
      get_attr:
      - undercloud_server
      - addresses
      - {get_param: private_net}
      - 0
      - addr
