#!/bin/bash
#
# Copyright 2014 Hewlett-Packard Development Company, L.P.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

ROOT_RM_PATHS="bin lib64 media opt sbin usr root etc lib mnt run srv var"

for _DIR in $ROOT_RM_PATHS ; do
    sudo rm -rf $TARGET_ROOT/$_DIR
done
# keep 99-tidy-logs happy
sudo mkdir -p $TARGET_ROOT/var/log
sudo mkdir $TARGET_ROOT/root

